//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIS_EGE_2013.FisEgeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:fbs:v2", ConfigurationName="FisEgeService.WSChecksSoap")]
    public interface WSChecksSoap {
        
        // CODEGEN: Generating message contract since message BatchCheckRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="urn:fbs:v2/BatchCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FIS_EGE_2013.FisEgeService.BatchCheckResponse BatchCheck(FIS_EGE_2013.FisEgeService.BatchCheckRequest request);
        
        // CODEGEN: Generating message contract since message BatchCheckNNRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="urn:fbs:v2/BatchCheckNN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FIS_EGE_2013.FisEgeService.BatchCheckNNResponse BatchCheckNN(FIS_EGE_2013.FisEgeService.BatchCheckNNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:fbs:v2/GetBatchCheckQuerySample", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetBatchCheckQuerySample();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:fbs:v2/GetBatchCheckQuerySampleNN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetBatchCheckQuerySampleNN();
        
        // CODEGEN: Generating message contract since message GetBatchCheckResultRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="urn:fbs:v2/GetBatchCheckResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FIS_EGE_2013.FisEgeService.GetBatchCheckResultResponse GetBatchCheckResult(FIS_EGE_2013.FisEgeService.GetBatchCheckResultRequest request);
        
        // CODEGEN: Generating message contract since message GetBatchCheckResultNNRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="urn:fbs:v2/GetBatchCheckResultNN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FIS_EGE_2013.FisEgeService.GetBatchCheckResultNNResponse GetBatchCheckResultNN(FIS_EGE_2013.FisEgeService.GetBatchCheckResultNNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:fbs:v2/GetSingleCheckQuerySample", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSingleCheckQuerySample();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:fbs:v2/GetSingleCheckQuerySampleNN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSingleCheckQuerySampleNN();
        
        // CODEGEN: Generating message contract since message SingleCheckRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="urn:fbs:v2/SingleCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FIS_EGE_2013.FisEgeService.SingleCheckResponse SingleCheck(FIS_EGE_2013.FisEgeService.SingleCheckRequest request);
        
        // CODEGEN: Generating message contract since message SingleCheckNNRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="urn:fbs:v2/SingleCheckNN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FIS_EGE_2013.FisEgeService.SingleCheckNNResponse SingleCheckNN(FIS_EGE_2013.FisEgeService.SingleCheckNNRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:fbs:v2")]
    public partial class UserCredentials : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string clientField;
        
        private string loginField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
                this.RaisePropertyChanged("Client");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("Login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchCheck", WrapperNamespace="urn:fbs:v2", IsWrapped=true)]
    public partial class BatchCheckRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:fbs:v2")]
        public FIS_EGE_2013.FisEgeService.UserCredentials UserCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:fbs:v2", Order=0)]
        public string queryXML;
        
        public BatchCheckRequest() {
        }
        
        public BatchCheckRequest(FIS_EGE_2013.FisEgeService.UserCredentials UserCredentials, string queryXML) {
            this.UserCredentials = UserCredentials;
            this.queryXML = queryXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchCheckResponse", WrapperNamespace="urn:fbs:v2", IsWrapped=true)]
    public partial class BatchCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:fbs:v2", Order=0)]
        public string BatchCheckResult;
        
        public BatchCheckResponse() {
        }
        
        public BatchCheckResponse(string BatchCheckResult) {
            this.BatchCheckResult = BatchCheckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchCheckNN", WrapperNamespace="urn:fbs:v2", IsWrapped=true)]
    public partial class BatchCheckNNRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:fbs:v2")]
        public FIS_EGE_2013.FisEgeService.UserCredentials UserCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:fbs:v2", Order=0)]
        public string queryXML;
        
        public BatchCheckNNRequest() {
        }
        
        public BatchCheckNNRequest(FIS_EGE_2013.FisEgeService.UserCredentials UserCredentials, string queryXML) {
            this.UserCredentials = UserCredentials;
            this.queryXML = queryXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BatchCheckNNResponse", WrapperNamespace="urn:fbs:v2", IsWrapped=true)]
    public partial class BatchCheckNNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:fbs:v2", Order=0)]
        public string BatchCheckNNResult;
        
        public BatchCheckNNResponse() {
        }
        
        public BatchCheckNNResponse(string BatchCheckNNResult) {
            this.BatchCheckNNResult = BatchCheckNNResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBatchCheckResult", WrapperNamespace="urn:fbs:v2", IsWrapped=true)]
    public partial class GetBatchCheckResultRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:fbs:v2")]
        public FIS_EGE_2013.FisEgeService.UserCredentials UserCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:fbs:v2", Order=0)]
        public string queryXML;
        
        public GetBatchCheckResultRequest() {
        }
        
        public GetBatchCheckResultRequest(FIS_EGE_2013.FisEgeService.UserCredentials UserCredentials, string queryXML) {
            this.UserCredentials = UserCredentials;
            this.queryXML = queryXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBatchCheckResultResponse", WrapperNamespace="urn:fbs:v2", IsWrapped=true)]
    public partial class GetBatchCheckResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:fbs:v2", Order=0)]
        public string GetBatchCheckResultResult;
        
        public GetBatchCheckResultResponse() {
        }
        
        public GetBatchCheckResultResponse(string GetBatchCheckResultResult) {
            this.GetBatchCheckResultResult = GetBatchCheckResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBatchCheckResultNN", WrapperNamespace="urn:fbs:v2", IsWrapped=true)]
    public partial class GetBatchCheckResultNNRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:fbs:v2")]
        public FIS_EGE_2013.FisEgeService.UserCredentials UserCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:fbs:v2", Order=0)]
        public string queryXML;
        
        public GetBatchCheckResultNNRequest() {
        }
        
        public GetBatchCheckResultNNRequest(FIS_EGE_2013.FisEgeService.UserCredentials UserCredentials, string queryXML) {
            this.UserCredentials = UserCredentials;
            this.queryXML = queryXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBatchCheckResultNNResponse", WrapperNamespace="urn:fbs:v2", IsWrapped=true)]
    public partial class GetBatchCheckResultNNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:fbs:v2", Order=0)]
        public string GetBatchCheckResultNNResult;
        
        public GetBatchCheckResultNNResponse() {
        }
        
        public GetBatchCheckResultNNResponse(string GetBatchCheckResultNNResult) {
            this.GetBatchCheckResultNNResult = GetBatchCheckResultNNResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SingleCheck", WrapperNamespace="urn:fbs:v2", IsWrapped=true)]
    public partial class SingleCheckRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:fbs:v2")]
        public FIS_EGE_2013.FisEgeService.UserCredentials UserCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:fbs:v2", Order=0)]
        public string queryXML;
        
        public SingleCheckRequest() {
        }
        
        public SingleCheckRequest(FIS_EGE_2013.FisEgeService.UserCredentials UserCredentials, string queryXML) {
            this.UserCredentials = UserCredentials;
            this.queryXML = queryXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SingleCheckResponse", WrapperNamespace="urn:fbs:v2", IsWrapped=true)]
    public partial class SingleCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:fbs:v2", Order=0)]
        public string SingleCheckResult;
        
        public SingleCheckResponse() {
        }
        
        public SingleCheckResponse(string SingleCheckResult) {
            this.SingleCheckResult = SingleCheckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SingleCheckNN", WrapperNamespace="urn:fbs:v2", IsWrapped=true)]
    public partial class SingleCheckNNRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:fbs:v2")]
        public FIS_EGE_2013.FisEgeService.UserCredentials UserCredentials;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:fbs:v2", Order=0)]
        public string queryXML;
        
        public SingleCheckNNRequest() {
        }
        
        public SingleCheckNNRequest(FIS_EGE_2013.FisEgeService.UserCredentials UserCredentials, string queryXML) {
            this.UserCredentials = UserCredentials;
            this.queryXML = queryXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SingleCheckNNResponse", WrapperNamespace="urn:fbs:v2", IsWrapped=true)]
    public partial class SingleCheckNNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:fbs:v2", Order=0)]
        public string SingleCheckNNResult;
        
        public SingleCheckNNResponse() {
        }
        
        public SingleCheckNNResponse(string SingleCheckNNResult) {
            this.SingleCheckNNResult = SingleCheckNNResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSChecksSoapChannel : FIS_EGE_2013.FisEgeService.WSChecksSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSChecksSoapClient : System.ServiceModel.ClientBase<FIS_EGE_2013.FisEgeService.WSChecksSoap>, FIS_EGE_2013.FisEgeService.WSChecksSoap {
        
        public WSChecksSoapClient() {
        }
        
        public WSChecksSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSChecksSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSChecksSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSChecksSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FIS_EGE_2013.FisEgeService.BatchCheckResponse FIS_EGE_2013.FisEgeService.WSChecksSoap.BatchCheck(FIS_EGE_2013.FisEgeService.BatchCheckRequest request) {
            return base.Channel.BatchCheck(request);
        }
        
        public string BatchCheck(FIS_EGE_2013.FisEgeService.UserCredentials UserCredentials, string queryXML) {
            FIS_EGE_2013.FisEgeService.BatchCheckRequest inValue = new FIS_EGE_2013.FisEgeService.BatchCheckRequest();
            inValue.UserCredentials = UserCredentials;
            inValue.queryXML = queryXML;
            FIS_EGE_2013.FisEgeService.BatchCheckResponse retVal = ((FIS_EGE_2013.FisEgeService.WSChecksSoap)(this)).BatchCheck(inValue);
            return retVal.BatchCheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FIS_EGE_2013.FisEgeService.BatchCheckNNResponse FIS_EGE_2013.FisEgeService.WSChecksSoap.BatchCheckNN(FIS_EGE_2013.FisEgeService.BatchCheckNNRequest request) {
            return base.Channel.BatchCheckNN(request);
        }
        
        public string BatchCheckNN(FIS_EGE_2013.FisEgeService.UserCredentials UserCredentials, string queryXML) {
            FIS_EGE_2013.FisEgeService.BatchCheckNNRequest inValue = new FIS_EGE_2013.FisEgeService.BatchCheckNNRequest();
            inValue.UserCredentials = UserCredentials;
            inValue.queryXML = queryXML;
            FIS_EGE_2013.FisEgeService.BatchCheckNNResponse retVal = ((FIS_EGE_2013.FisEgeService.WSChecksSoap)(this)).BatchCheckNN(inValue);
            return retVal.BatchCheckNNResult;
        }
        
        public string GetBatchCheckQuerySample() {
            return base.Channel.GetBatchCheckQuerySample();
        }
        
        public string GetBatchCheckQuerySampleNN() {
            return base.Channel.GetBatchCheckQuerySampleNN();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FIS_EGE_2013.FisEgeService.GetBatchCheckResultResponse FIS_EGE_2013.FisEgeService.WSChecksSoap.GetBatchCheckResult(FIS_EGE_2013.FisEgeService.GetBatchCheckResultRequest request) {
            return base.Channel.GetBatchCheckResult(request);
        }
        
        public string GetBatchCheckResult(FIS_EGE_2013.FisEgeService.UserCredentials UserCredentials, string queryXML) {
            FIS_EGE_2013.FisEgeService.GetBatchCheckResultRequest inValue = new FIS_EGE_2013.FisEgeService.GetBatchCheckResultRequest();
            inValue.UserCredentials = UserCredentials;
            inValue.queryXML = queryXML;
            FIS_EGE_2013.FisEgeService.GetBatchCheckResultResponse retVal = ((FIS_EGE_2013.FisEgeService.WSChecksSoap)(this)).GetBatchCheckResult(inValue);
            return retVal.GetBatchCheckResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FIS_EGE_2013.FisEgeService.GetBatchCheckResultNNResponse FIS_EGE_2013.FisEgeService.WSChecksSoap.GetBatchCheckResultNN(FIS_EGE_2013.FisEgeService.GetBatchCheckResultNNRequest request) {
            return base.Channel.GetBatchCheckResultNN(request);
        }
        
        public string GetBatchCheckResultNN(FIS_EGE_2013.FisEgeService.UserCredentials UserCredentials, string queryXML) {
            FIS_EGE_2013.FisEgeService.GetBatchCheckResultNNRequest inValue = new FIS_EGE_2013.FisEgeService.GetBatchCheckResultNNRequest();
            inValue.UserCredentials = UserCredentials;
            inValue.queryXML = queryXML;
            FIS_EGE_2013.FisEgeService.GetBatchCheckResultNNResponse retVal = ((FIS_EGE_2013.FisEgeService.WSChecksSoap)(this)).GetBatchCheckResultNN(inValue);
            return retVal.GetBatchCheckResultNNResult;
        }
        
        public string GetSingleCheckQuerySample() {
            return base.Channel.GetSingleCheckQuerySample();
        }
        
        public string GetSingleCheckQuerySampleNN() {
            return base.Channel.GetSingleCheckQuerySampleNN();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FIS_EGE_2013.FisEgeService.SingleCheckResponse FIS_EGE_2013.FisEgeService.WSChecksSoap.SingleCheck(FIS_EGE_2013.FisEgeService.SingleCheckRequest request) {
            return base.Channel.SingleCheck(request);
        }
        
        public string SingleCheck(FIS_EGE_2013.FisEgeService.UserCredentials UserCredentials, string queryXML) {
            FIS_EGE_2013.FisEgeService.SingleCheckRequest inValue = new FIS_EGE_2013.FisEgeService.SingleCheckRequest();
            inValue.UserCredentials = UserCredentials;
            inValue.queryXML = queryXML;
            FIS_EGE_2013.FisEgeService.SingleCheckResponse retVal = ((FIS_EGE_2013.FisEgeService.WSChecksSoap)(this)).SingleCheck(inValue);
            return retVal.SingleCheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FIS_EGE_2013.FisEgeService.SingleCheckNNResponse FIS_EGE_2013.FisEgeService.WSChecksSoap.SingleCheckNN(FIS_EGE_2013.FisEgeService.SingleCheckNNRequest request) {
            return base.Channel.SingleCheckNN(request);
        }
        
        public string SingleCheckNN(FIS_EGE_2013.FisEgeService.UserCredentials UserCredentials, string queryXML) {
            FIS_EGE_2013.FisEgeService.SingleCheckNNRequest inValue = new FIS_EGE_2013.FisEgeService.SingleCheckNNRequest();
            inValue.UserCredentials = UserCredentials;
            inValue.queryXML = queryXML;
            FIS_EGE_2013.FisEgeService.SingleCheckNNResponse retVal = ((FIS_EGE_2013.FisEgeService.WSChecksSoap)(this)).SingleCheckNN(inValue);
            return retVal.SingleCheckNNResult;
        }
    }
}
